### ISSUE TITLE
How to style navigation elements?

### ISSUE THREAD

**Issue by dpdonohue** [ethanhann/eeh-navigation#1]
For example you generate the top header bar with this
`<nav class="navbar navbar-default navbar-static-top eeh-navigation" role="navigation">`
How can I change it to have a different background, like "primary"?

**Comment by ethanhann** [comment]
Hello. My directive doesn't provide a way to do that at the moment. Here are some options...
1. You can override/extend the existing Bootstrap classes with Sass or Less - effectively creating your own Bootstrap theme. 
2. You can override any of the classes in an external stylesheet with plain old CSS.
3. You can fork the repo, make the classes configurable with ng-class, and submit a pull request.

**Comment by ethanhann** [comment]
Note: I implemented option 3 which will be available in the next release. See: https://github.com/ethanhann/eeh-navigation/blob/master/src/navbar/eeh-navigation-navbar-directive.js#L26
