### ISSUE TITLE
Nested Sidebar Menu Items - on collapse of sidebar menu, nested menu hides too

### ISSUE THREAD

**Issue by mominsamir** [ethanhann/eeh-navigation#12]
Hi Ethan,

While using nested side bar menu - if sidebar is collapse nested menu root hide, while side bar  on open mode nested menu work as expected. screen shots attached. 

can u tell me what i am doing wrong. I am using version 3.3.

<code>
    .config(['$stateProvider','eehNavigationProvider','$translateProvider',function ($stateProvider,eehNavigationProvider,$translateProvider) {

```
$stateProvider.state('home',{
    url : '/',
    templateUrl: 'views/main.html',
    controller: 'MainCtrl'
}).state('about',{
    url : '/about',
    templateUrl: 'views/about.html',
    controller: 'AboutCtrl'
});

eehNavigationProvider.navbarBrand.text = 'My Product';
eehNavigationProvider.navbarBrand.href = '/home';

eehNavigationProvider.sidebarMenuItem('homez', 
{
      text: 'Home',
      iconClass: 'fa-home',
      href: '/#/about' 
});


eehNavigationProvider
  .sidebarMenuItem('root', { // The root level of the nested menu.
      text: 'Root',
      isCollapsed: false
  })
  .sidebarMenuItem('root.foo', { // The first item under root.
      text: 'Foo',
      href: '/some/path'
  })
  .sidebarMenuItem('root.bar', { // The second item under root.
      text: 'Bar',
      href: '/some/path'
  })
  .sidebarMenuItem('root.baz', { // The third item under root.
      text: 'Baz'
  })
  .sidebarMenuItem('root.baz.qux', { // The first item under root.baz
      text: 'Quz',
      href: '/some/path'
  })
  .sidebarMenuItem('root.baz.quux', { // The second item under root.baz
      text: 'Quux',
      href: '/some/path'
  });
```

  }]);
</code>

![sidebar-open-mode](https://cloud.githubusercontent.com/assets/9468921/8021463/1d723d04-0cbe-11e5-9436-6f5a0142a948.png)
![sidebar-collapse-mode](https://cloud.githubusercontent.com/assets/9468921/8021462/1d7129b4-0cbe-11e5-9ed4-bebdaf193f4a.png)

**Comment by ethanhann** [comment]
You are not doing anything wrong. Nested sidebar items are not available when the sidebar is collapsed in version 3.3.0. The feature was added in [4.0.0-alpha3](https://github.com/ethanhann/eeh-navigation/releases/tag/4.0.0-alpha3). A beta, or possibly stable, release of version 4.0.0 might happen this weekend or next week. Version 4.0.0 is feature complete, but I am still in the process of creating documentation for it.

**Comment by mominsamir** [comment]
thanks for update closing issue..
