### ISSUE TITLE
How to dynamically add menu items?

### ISSUE THREAD

**Issue by mbukosky** [ethanhann/eeh-navigation#13]
Hello,

From reading over the documents it says that 

> It is possible to create a menu item with the eehNavigation service, but it is not recommended. Instead, create the menu item in .config and only do minimal wiring/contextual configuration elsewhere with the eehNavigation service.

If this is the case, how would you go about adding dynamic menu items? I have a use case where the menu items will be returned from a service. But given the life-cycle of angular, it is not possible to use services inside a config. Any suggestions?

Thanks for the support and great app

**Comment by ethanhann** [comment]
The pattern I describe in the docs is just a suggestion to keep your app from becoming littered with menu item creation code. In practice, you can use whatever initialization pattern fits your needs. For example, you can initialize all your menu items in a parent controller or your own service that you created specifically for menu item creation. You can of course inject whatever services you need into that controller or service.

**Comment by mbukosky** [comment]
Thanks for the feedback, but I am having trouble using the _eehNavigation_ service/provider inside the controller. Angular doesn't support using a provider inside a [controller](https://code.angularjs.org/1.2.28/docs/guide/di), so I used the _eehNavigation_ service which I found from your demo source. The code is able to run without any error but the view doesn't update. I am only able to get side bar menu items from within the config. Here is some sample code

``` html
<eeh-navigation>
   <div ui-view></div>
</eeh-navigation
```

``` javascript
'use strict';

angular.module('Foo')
  .controller('FooCtrl', ['$scope', 'eehNavigation', function($scope, eehNavigation) {

    eehNavigation
      .sidebarMenuItem('foo', {
        text: 'Foo Bar',
        iconClass: 'fa-home',
        state: 'foo',
        weight: 0
      });

    //View doesn't display "Foo Bar" menu
  }]);
```

I feel like I am missing something simple.

**Comment by ethanhann** [comment]
It is hard to say what is going wrong without a more complete example. I can help you debug the issue if you create a more complete example in [Plunker](http://plnkr.co/).

**Comment by mbukosky** [comment]
I just noticed that you release 4.0.0. I am going to update my example and see if that resolves the issue. Thanks for all the help.

**Comment by mbukosky** [comment]
I was finally able to get the dynamic loading working. I resolved it by adding a controller to the index.html. This controller will get loaded during the digest and add content to the menu bar. Thanks for all your help

I put together a demo. Please see below

<p data-height="283" data-theme-id="0" data-slug-hash="qdVBWe" data-default-tab="result" data-user="mbukosky" class='codepen'>See the Pen <a href='http://codepen.io/mbukosky/pen/qdVBWe/'>eeh-navigation</a> by Mike Bukosky (<a href='http://codepen.io/mbukosky'>@mbukosky</a>) on <a href='http://codepen.io'>CodePen</a>.</p>

<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

**Comment by mbukosky** [comment]
Sorry to reopen this but I was able to create an example where loading for controller doesn't work. I added a timeout to simulate a async http request. I have updated my code pen example to show that the 'three' menu is not added.

I believe this is occurring because the digest has already fired. I tried adding a $scope.$apply but that didn't work either. 

Any ideas?

``` js
    setTimeout(function() {
      eehNavigation
        .menuItem('foo.three', {
          text: 'Three',
          iconClass: 'fa fa-cube',
          state: 'foo.three'
        });
    }, 1000);
```

**Comment by mbukosky** [comment]
After adding a deep watch to menuItems, the sidebar refreshed correctly

_before_

``` js
scope.$watch(menuItems, function() {
    if (angular.isUndefined(scope.menuName)) {
        return;
    }
    scope.sidebarMenuItems = eehNavigation.menuItemTree(scope.menuName);
});
```

_after_

``` js
scope.$watch(menuItems, function() {
    if (angular.isUndefined(scope.menuName)) {
        return;
    }
    scope.sidebarMenuItems = eehNavigation.menuItemTree(scope.menuName);
}, true);
```
