### ISSUE TITLE
menu JSON

### ISSUE THREAD

**Issue by 170181** [ethanhann/eeh-navigation#16]
mounting the menu from a JSON (eehnavigation)

**Comment by ethanhann** [comment]
You create menu items with the menuItem method of the eehNavigation service (see [Getting Started](http://www.ethanhann.com/eeh-navigation/#/docs/getting-started)). I assume you would retrieve your JSON object with $http, then loop over your object, calling eehNavigationProvider.menuItem() for each menuItem you want to add. If that doesn't answer your question please create a plunker with an example of where you are running into trouble.

**Comment by 170181** [comment]
obrigado, vou tentar ...

2015-06-30 18:33 GMT-03:00 Ethan Hann <notifications@github.com>:

> You create menu items with the menuItem method of the eehNavigation
> service (see Getting Started
> <http://www.ethanhann.com/eeh-navigation/#/docs/getting-started>). I
> assume you query your JSON with $http, then loop over your JSON object,
> calling eehNavigationProvider.menuItem() for each menuItem you want to add.
> If that doesn't answer your question please create a plunker with an
> example of where you are running into trouble.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethanhann/eeh-navigation/issues/16#issuecomment-117351974>
> .
>



-- 
web

**Comment by 170181** [comment]
obrigado, vou tentar ...

2015-06-30 23:13 GMT-03:00 Marcos Bazilio <msbazilio@gmail.com>:

> obrigado, vou tentar ...
>
> 2015-06-30 18:33 GMT-03:00 Ethan Hann <notifications@github.com>:
>
>> You create menu items with the menuItem method of the eehNavigation
>> service (see Getting Started
>> <http://www.ethanhann.com/eeh-navigation/#/docs/getting-started>). I
>> assume you query your JSON with $http, then loop over your JSON object,
>> calling eehNavigationProvider.menuItem() for each menuItem you want to add.
>> If that doesn't answer your question please create a plunker with an
>> example of where you are running into trouble.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ethanhann/eeh-navigation/issues/16#issuecomment-117351974>
>> .
>>
>
>
>
> --
> web
>



-- 
web

**Comment by 170181** [comment]
thank you, I'll try ...

2015-06-30 23:14 GMT-03:00 Marcos Bazilio msbazilio@gmail.com:

> obrigado, vou tentar ...
> 
> 2015-06-30 23:13 GMT-03:00 Marcos Bazilio msbazilio@gmail.com:
> 
> > obrigado, vou tentar ...
> > 
> > 2015-06-30 18:33 GMT-03:00 Ethan Hann notifications@github.com:
> > 
> > > You create menu items with the menuItem method of the eehNavigation
> > > service (see Getting Started
> > > http://www.ethanhann.com/eeh-navigation/#/docs/getting-started). I
> > > assume you query your JSON with $http, then loop over your JSON object,
> > > calling eehNavigationProvider.menuItem() for each menuItem you want to add.
> > > If that doesn't answer your question please create a plunker with an
> > > example of where you are running into trouble.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/ethanhann/eeh-navigation/issues/16#issuecomment-117351974
> > > .
> > 
> > ## 
> > 
> > web
> 
> ## 
> 
> web

## 

web

**Comment by 170181** [comment]
Good morning, I could not put the json in sidebarMenuItem within the
eehNavigationProvider.
You have any examples that I can follow?

2015-06-30 23:15 GMT-03:00 Marcos Bazilio msbazilio@gmail.com:

> thank you, I'll try ...
> 
> 2015-06-30 23:14 GMT-03:00 Marcos Bazilio msbazilio@gmail.com:
> 
> > obrigado, vou tentar ...
> > 
> > 2015-06-30 23:13 GMT-03:00 Marcos Bazilio msbazilio@gmail.com:
> > 
> > > obrigado, vou tentar ...
> > > 
> > > 2015-06-30 18:33 GMT-03:00 Ethan Hann notifications@github.com:
> > > 
> > > > You create menu items with the menuItem method of the eehNavigation
> > > > service (see Getting Started
> > > > http://www.ethanhann.com/eeh-navigation/#/docs/getting-started). I
> > > > assume you query your JSON with $http, then loop over your JSON object,
> > > > calling eehNavigationProvider.menuItem() for each menuItem you want to add.
> > > > If that doesn't answer your question please create a plunker with an
> > > > example of where you are running into trouble.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/ethanhann/eeh-navigation/issues/16#issuecomment-117351974
> > > > .
> > > 
> > > ## 
> > > 
> > > web
> > 
> > ## 
> > 
> > web
> 
> ## 
> 
> web

## 

web

**Comment by ethanhann** [comment]
sidebarMenuItem does not exist in version 4.x. You would use menuItem, as the  [Getting Started](http://www.ethanhann.com/eeh-navigation/#/docs/getting-started) doc explains. The docs web app itself is a functional example of how to use menuItem. Take a look at this: https://github.com/ethanhann/eeh-navigation/blob/master/docs/src/app/index.js
