### ISSUE TITLE
Brand Logo is missing

### ISSUE THREAD

**Issue by mackwan84** [ethanhann/eeh-navigation#17]
``` html
<eeh-navigation-navbar menu-name="publicMenu.name" nav-class="publicMenu.css" brand-text="publicMenu.text" brand-src="publicMenu.logo" brand-state="publicMenu.state"></eeh-navigation-navbar>
```

Even though I set the brand-src attribute, the brand logo is still missing. Would you please help us fix this issue? Thanks.

**Comment by ethanhann** [comment]
Thank you for reporting the issue. Try the latest release (4.1.2).
