### ISSUE TITLE
Navigation inside a page

### ISSUE THREAD

**Issue by redaz808** [ethanhann/eeh-navigation#18]
Hi,

I have a navigation menu with 3 menu Items ( menuItem1, menuItem2, menuItem3)
The navigation works file and the corresponding state is executed.

<pre>
$stateProvider
        .state('demo', {
            abstract: true,
            templateUrl: 'app.html'
        })
        .state('demo.menuItem1', {
            templateUrl: 'example1.html'
        })
        .state('demo.menuItem2', {
            templateUrl: 'list.html'
        })
        .state('demo.menuItem2.detail',{
            templateUrl: 'list-detail.html'
        })
        .state('demo.menuItem3', {
            templateUrl: 'example2.html'
        })
        

    eehNavigationProvider.iconBaseClass('glyphicon');

    eehNavigationProvider
        .menuItem('menuOne.menuItem1', {
            text: 'MenuItem1',
            iconClass: 'glyphicon-home',
            state: 'demo.menuItem1',
            weight: -10
        })
        .menuItem('menuOne.menuItem2', {
            text: 'MenuItem2',
            iconClass: 'glyphicon-list',
            state: 'demo.menuItem2',
            weight: -9
        })
         .menuItem('menuOne.menuItem2', {
            text: 'MenuItem3',
            iconClass: 'glyphicon-list',
            state: 'demo.menuItem3',
            weight: -8
        })
</pre>

Now I am trying to navigate inside a view of a given state. For example let us say that I have a list in the state corresponding to menuItem1 and I want to navigate to the detail of each list item inside that list.
If I click inside a the list of demo.menuItem2 on the link:

```
 <a ui-sref="demo.menuItem2.detail">Detail</a>
```

The state is not changed. Do you know how this could be done?

Thanks,

**Comment by ethanhann** [comment]
It sounds like you aren't using UI Router 100% correctly. I recommend that you verify that your states and templates are setup correctly and are navigable independent of the nav module. If they are, setup a plunk (or similar) and I'll take a look.
