### ISSUE TITLE
Can I have the source code of this example one the website please ?

### ISSUE THREAD

**Issue by alexliubj** [ethanhann/eeh-navigation#19]
http://www.ethanhann.com/eeh-navigation-demo/#/navbar-sidebar

Where I can find this one please?

**Comment by ethanhann** [comment]
https://github.com/ethanhann/eeh-navigation-demo

**Comment by ethanhann** [comment]
Specifically,

https://github.com/ethanhann/eeh-navigation-demo/tree/master/src/app/navigation/

And...

https://github.com/ethanhann/eeh-navigation-demo/tree/master/src/app/app.js

**Comment by alexliubj** [comment]
Thanks :) :+1:

**Comment by smannaoh** [comment]
Hi Ethan,
I have downloaded the demo example eeh-navigation-demo-master. Can you please outline the steps how to build and run the demo? I have run 'npm install' in the eeh-navigation-demo-master. I am not sure what to do after that. Please help.
Thanks.
