### ISSUE TITLE
Adding items in .config 

### ISSUE THREAD

**Issue by YossiH** [ethanhann/eeh-navigation#2]
This code adds sidebar menuitems without error, but the menuitems are not displayed.

I'm sure the code is executed, because the 'hi from foreach' is displayed on the console, also, i stepped through the code and I'm sure it is being processed.

Any suggestions?

```
    .config(["initProvider", 'eehNavigationProvider', function(initProvider, eehNavigationProvider) {
            initProvider.$get().then(function (init) {
                    angular.forEach(init, function (value, key) {

                        eehNavigationProvider.sidebarMenuItem(value.name, {
                            text: value.text,
                            iconClass: value.iconClass,
                            href: value.url || '/',
                            isCollapsed: value.isCollapsed,
                            isVisible: value.isVisible
                        });
                        console.log('hi from foreach');
                    })
            }
```

**Comment by ethanhann** [comment]
Did you include the eeh-navigation directive in one of your templates?

**Comment by YossiH** [comment]
I included the script, and css. There are no errors, only the menu items come up empty. See attached image: 
![eeh_menu](https://cloud.githubusercontent.com/assets/6239273/6157291/34f09dfa-b20e-11e4-96b5-75354094fafc.png)

**Comment by YossiH** [comment]
I did not answer your question though ;), yes, the template is included in my index.html (at the moment).

**Comment by ethanhann** [comment]
When exactly is in the _init_ variable? Can you console.log it and let me know?

**Comment by YossiH** [comment]
Thanks Ethan for your quick response.

Please note, that the  eehNavigationProvider.sidebarMenuItem code is certainly run, and without error, I had a breakpoint in inspector to validate it.

(DS is my data provider.)

```
    module.service('init', function initFactory(DS) {

        return DS.defineResource('init', {
            name: 'init',
            idAttribute: 'id',
            endpoint: '/init',
            basePath: 'http://localhost:63342/api'
        }).findAll({idAttribute: 'id'});

    })


    .provider("initProvider", ['DSProvider', function (DSProvider) {

            this.$get = ["init", function initFactory(init) {
                return new init(init);
            }]

    }])
```

in case it helps, here is a sampling my JSON

{
    "id": 1,
    "name": “axContainer.part1",
    "text": “Part 1",
    "isCollapsed": true,
    "iconClass" : "fa-building",
    "isVisible": true,
    "weight": 0
},
{
    "id": 2,
    "name" : “axContainer.part1.room20",
    "text" : “Room 20",
    "iconClass" : "fa-circle",
    "state" : "axContainer.part1.room20",
    "url": "api/data/part1/room20",
    "templateUrl": "api/data/part1/room20",
    "controller": "api/data/part1/room20",
    "isVisible": true,
    "weight" : 0
},
{
    "id": 2,
    "name" : “axContainer.part1.room20",
    "text" : “Room 21",
    "iconClass" : "fa-circle",
    "state" : "axContainer.part1.room21",
    "url": "api/data/part1/room21",
    "templateUrl": "api/data/part1/room21",
    "controller": "api/data/part1/room21",
    "isVisible": true,
    "weight" : 0
}

**Comment by ethanhann** [comment]
I think I know what the issue is. There isn't a root menu item called "axContainer" so your menu items are effectively orphaned. See the [Nested Sidebar Menu Items](http://www.ethanhann.com/eeh-navigation/configuration/nested-sidebar-menu-items.html) doc for an example of how to nest sidebar menu items.

If you do not want to nest your sidebar menu items, then the names should be something like "axContainerPart1" and "axContainerPart1Room20" (sans periods).

Let me know if that resolves your issue.

**Comment by YossiH** [comment]
Resolved. Thank you!

**Comment by ethanhann** [comment]
I am glad I was able to help. Please consider starring the repo if you decide you like the project.
