### ISSUE TITLE
Defaulting Sidebar Closed missing '.hidden' class on text

### ISSUE THREAD

**Issue by ghost** [ethanhann/eeh-navigation#23]
Thanks for all of your work on this directive it is extremely handy and exactly what I needed.

I have gone through the examples as best I could dissect them - it would be helpful if the examples were isolated to a single application each rather than all of them nested within the main application as its difficult to break out the individual parts....regardless I have an issue where it loads the icons in a collapsed sidebar (using font awesome) but the text is visible (is missing the the ".hidden" css class) and displaying as 'underlined' with the initial load. If I click the 'expand' icon it expands (still the text is underlined) and then click 'collapse' everything looks good the text has the 'hidden' class .... code looks like 

```
<eeh-navigation-sidebar menu-name="'bar'" 
        search-input-icon-class="'fa-search'" 
        sidebar-is-collapsed="true" 
        sidebar-collapsed-icon-class="'fa-arrow-right'" 
        sidebar-expanded-icon-class="'fa-arrow-left'">
             <ui-view></ui-view>
</eeh-navigation-sidebar>

   var app = angular.module('myapp', [
        'eehNavigation',
        'pascalprecht.translate',
        'ui-router',
        'ngSanitize',
        'ngResource',
        'ngAnimate'
   ]);

app.config(['eehNavigationProvider', function (eehNavigationProvider) {
   $stateProvider.state('somestate',
   {
          url: '/someurl'
          templateUrl: '/sometemplate.html'
   }),
    eehNavigationProvider.iconBaseClass("fa")  
    eehNavigationProvider
      .menuItem('foo.user', {
           text: 'Me',
           iconClass: 'fa-user'
           state: 'somstate'
       })
}]);
```

I know that I can fix the underlined text with custom CSS. I am only mentioning it as it may help to troubleshoot why it is displaying at all.

**Comment by ethanhann** [comment]
I'll look into fixing this issue probably this weekend. I want to do examples like how the [ng-table](http://ng-table.com/#/pagination/demo-pager-basic) site does them, but I haven't had the time.

**Comment by ethanhann** [comment]
@MigoFast Can you provide a screenshot? I can't reproduce the issue.

**Comment by anthonyraymond** [comment]
For me, it happens because, the list of item is not rendered on the page when `scope.$on("$includeContentLoaded", ...` fire `setTextCollapseState();`

**Comment by anthonyraymond** [comment]
By the way, thanks for `eeh-navigation` you did a good job :smile:

**Comment by ethanhann** [comment]
#35 resolves this
