### ISSUE TITLE
Compatibility with ui-bootstrap Ver: 0.14.3

### ISSUE THREAD

**Issue by Furburger** [ethanhann/eeh-navigation#24]
Hi

I love your navigation directives - thanks very much. 

Just a small thing . . .

I need ui-bootstrap Ver: 0.14.3 for other dependencies, but it seems as if your directives are using _deprecated uib directives_. I get the following messages in the console:

**collapse is now deprecated. Use uib-collapse instead.
$tooltip is now deprecated. Use $uibTooltip instead.
DropdownController is now deprecated. Use UibDropdownController instead.**
... etc

Would it be possible to upgrade to the latest version of ui-bootstrap?

**Comment by ethanhann** [comment]
That shouldn't be too much work. I'll try to find some time to do it this weekend.

**Comment by ethanhann** [comment]
Resolved by 578c71a21f955a893bf4c21c60d895439f2bd21b
