### ISSUE TITLE
Search input callback not called on search submit

### ISSUE THREAD

**Issue by ghost** [ethanhann/eeh-navigation#40]
I have a root controller that 'resolves' the currently logged in user and adds that user to a service - I just want to access this service and display this user object in the sidebar so I mimicked how the search input is set up but I can't seem to get access to the service at any point in the directive - I see I can pass a function of sorts to the search submit but I don't see that played through - where should the submit function definition be assigned?

**Comment by ethanhann** [comment]
I haven't had a chance to look at this issue. I might have some time on Sunday.

**Comment by patrickdronk** [comment]
Hi Ethanhann, did you had any chance by looking into it? If fixed it. But it's not a nice fix. Could you else give me a direction as how this can be solved. I don't want to change to much things.

**Comment by ethanhann** [comment]
Hi @patrickdronk. I haven't fixed it. If you want to submit your fix as a PR I can take a look at it.

**Comment by ethanhann** [comment]
I just tested the search input. It works correctly: http://codepen.io/ethanhann/pen/QjXxGX?editors=1010

**Comment by patrickdronk** [comment]
Guess my interpretation of the search has been different, I thought it was used to search within the sidebar.
