### ISSUE TITLE
Adding menu items in a controller doesn't seem to work reliably

### ISSUE THREAD

**Issue by aschaible** [ethanhann/eeh-navigation#45]
Looking through previous issues, this code came up:

http://codepen.io/mbukosky/pen/qdVBWe/

Doesn't work for me.  The controller adds a third menu item, but it does not appear.  If you collapse the menu, it does add the third menu in the display.

I am trying to build a menu dynamically.  I have the directive in my HTML, and when I try to use the API in the controller, no menu items are added.  If .menuItem is called directly in the controller (meaning not after a promise is returned) menu items are added, but they are not added if the API is used after a promise, or as a part of setTimeout().

**Comment by ethanhann** [comment]
I usually define all the menu items up front. I can't vouch for how well it works when building menus dynamically. Calling the nav service's menuItemTree() method after you add your menu items dynamically might help: https://github.com/ethanhann/eeh-navigation/blob/master/src/core/eeh-navigation-service.js#L392
