### ISSUE TITLE
How to pass $stateParams

### ISSUE THREAD

**Issue by voznik** [ethanhann/eeh-navigation#47]
hi! i need to pass $stateParams to my dynamic menu. how can i do it right?

**Comment by ethanhann** [comment]
I've never tried that. I don't know if it is currently possible. You could try setting the menu items's state to an expression that includes whatever state param you are using. Keep in mind that when you dynamically modify a menu you have to call the eehNavigation.menuItemTree('myMenu') method. That 
might work. Let me know what happens.

**Comment by warapitiya** [comment]
+1

@ethanhann  can you provide us a sample if it works?

**Comment by ethanhann** [comment]
It seems to be possible: http://codepen.io/anon/pen/JXPKGz

**Comment by warapitiya** [comment]
:+1: nice
