### ISSUE TITLE
Minification problem

### ISSUE THREAD

**Issue by marianoc84** [ethanhann/eeh-navigation#5]
I used eeh-navigation.js (unminified version) inside my project and having problem with `ActiveParentMenuItemDirective` when JS is bundeld and minified.
The incriminated code was at line 105:
`angular.module("eehNavigation").directive("eehActiveParentMenuItem", ActiveParentMenuItemDirective);`

I resolved declaring location:
`angular.module("eehNavigation").directive("eehActiveParentMenuItem", ['$location', ActiveParentMenuItemDirective]);`

**Comment by ethanhann** [comment]
Thank you for reporting this issue. I am now building this library with ngAnnotate. Release 3.2.1 is [properly annotated](https://github.com/ethanhann/eeh-navigation/commit/01a98e55fd26c3694da6d105f34fcbfaa758175e#diff-37ab11bb71529a3b5ec25a748bb73d07R105).
