### ISSUE TITLE
 eeh-navigation-sidebar  Microsoft Edge Issue

### ISSUE THREAD

**Issue by lukaphp** [ethanhann/eeh-navigation#50]
only with Microsoft Edge browser I got this issue when  eeh-navigation-sidebar is rendered:

TypeError: Object doesn't support property or method 'matches'
at Anonymous function (http://localhost:2500/bower_components/eeh-navigation/dist/eeh-navigation.js:390:25)
.....................................................................

This is the line concerned:
`var arrowIconElements = Array.prototype.filter.call(sidebarMenuItems, function(item) {
                        return item.matches(".sidebar-arrow");
                    });`

**Comment by lukaphp** [comment]
Ok solved with a workaround.... The 'matches' method not seem to be supported on Edge...
I rewrited the method with this code:
`var allMenuItemTextElements = Array.prototype.filter.call(sidebarMenuItemText, function(item) {
                        var classes = item.className.split(' ');
                        var _class; var i = 0; var found = false;
                          while (i < classes.length && !found) {
                              if (classes[i]=='menu-item-text') {
                                _class = classes[i];
                                found = true;
                              } else ++i;
                          }
                        return _class;
                    });`

Now it works even on MS Edge

**Comment by ethanhann** [comment]
Resolved by 8a00ba0f952b904ff52a32ec2a474f70089ec76e
...added a polyfill for matches.
