### ISSUE TITLE
How to target the sidebar CSS elements to apply custom styling?

### ISSUE THREAD

**Issue by RipleWare** [ethanhann/eeh-navigation#52]
Is there any examples that demonstrate how to target the CSS styling of the sidebar?  In your examples there is no CSS applied, but I am struggling to find what elements apply to the sidebar.  Even applying an override to the `nav-class` elements doesn't seem to be helping.

**Comment by ethanhann** [comment]
There is a top level class called "eeh-navigation-sidebar' that you can target. The nav-class attribute should allow you to specify your own custom class. You can also add whatever class you want in the directive or in a wrapping element. 

Like... 

``` html
<eeh-navigation-sidebar class="my-class"></eeh-navigation-sidebar>
```

Or...

``` html
<div class="my-class"><eeh-navigation-sidebar></eeh-navigation-sidebar></div>
```

**Comment by ethanhann** [comment]
Related: #46
