### ISSUE TITLE
Menu item duplicated when a function is assigned to it

### ISSUE THREAD

**Issue by mmteyrek** [ethanhann/eeh-navigation#53]
Hello,
I'm facing a strange issue, when I assign a function to an item. The item is duplicated in the menu !
Any idea about this issue?
Thank yon in advance.

**Comment by ethanhann** [comment]
The click, state, and href properties are mutually exclusive. If you add more than one to a menu item you will experience this issue.

**Comment by mmteyrek** [comment]
OK, I get it : I have to chose on thsese properties because they are using ng-click all of them.
Thank You
