### ISSUE TITLE
eeh-navigation-sidebar custom field.

### ISSUE THREAD

**Issue by vazh** [ethanhann/eeh-navigation#54]
sorry if the title is kinda weird, dont know how to express it.

currently at the top of the sidebar there's a search field in it.

i want remove/replace it with a logo or something else.

can it be done ? if so, how ? can you point me to some example or clue ?

thanks.

**Comment by ethanhann** [comment]
There isn't a way to do that out of the box. You could manipulate the sidebar with your own custom directive to add whatever you need to it.

**Comment by vazh** [comment]
alright then, i thought there is a way to do that. thanks a lot m8. much appreciated.

i have another question regarding sidebar+metismenu. how to make the collapsible menu to open one at a time, so if i open another one, the former one close automatically.

should i open another issue ?

**Comment by ethanhann** [comment]
I don't think you can use metisMenu with the sidebar. The sidebar has its own Angular-centric collapse logic. You could use metisMenu with the eeh-navigation-menu directive to roll your own sidebar.

**Comment by vazh** [comment]
css isn't really my forte,
i actually already did the sidebar with metismenu. just the menu can be all expanded.
![image](https://cloud.githubusercontent.com/assets/3176112/15562851/3a2193d8-232d-11e6-8206-730212bdff64.png)

**Comment by ethanhann** [comment]
With metis you set the toggle option to true to accomplish the behavior you desire. If you are doing that and it still isn't working, then the sidebar's collapse logic is probably taking precedence over whatever metis is doing.

**Comment by vazh** [comment]
yeah, still aint working. probably what you're saying.

i'll just try using eeh-navigation-menu later.

thanks a lot. much appreciated.
