### ISSUE TITLE
eeh-navigation-sidebar

### ISSUE THREAD

**Issue by niltonjacintho** [ethanhann/eeh-navigation#64]
My system already has many pages and now i try to use eeh-navigation-sidebar. Before i try to use it i had a Shell controler (and page) and i include it in all my pages html. Ok works fine!! But when i use eeh-navigation-sidebar inside this same controller / page, all my pages lost his definition!! Looks like eeh-navigation-sidebar include a new frame or something like this.

**this is my eeh-navigation-sidebar:**

  .config(['eehNavigationProvider', function(eehNavigationProvider) {
    eehNavigationProvider.iconBaseClass("fa")
      // Add a menu item that links to "/home" to the "bar" menu.
    eehNavigationProvider
      .menuItem('bar.renda', {
        text: 'Rendas',
        iconClass: 'fa-ticket',
      })
      .menuItem('bar.renda.manual', {
        text: 'Renda Manual',
        iconClass: 'fa-hand-paper-o',
      })
      .menuItem('bar.renda.automatica', {
        text: 'Carga de rendas',
        iconClass: 'fa-cloud-upload',
      })
      .menuItem('bar.renda.gestao', {
        text: 'Gestão de Rendas',
        iconClass: 'fa-check-square',
      })
      .menuItem('bar.depara', {
        text: 'De Para(s)',
        iconClass: 'fa-home',
      })
      .menuItem('bar.depara.Rendas', {
        text: 'De Para de Rendas',
        iconClass: 'fa-home',
      })
      .menuItem('bar.depara.Programacao', {
        text: 'De Para de programação)',
        iconClass: 'fa-home',
      })
      .menuItem('bar.exportar', {
        text: 'Exportar Dados',
        iconClass: 'fa-home',
      })
      .menuItem('bar.exportar.RendasFimSemana', {
        text: 'Exportar Dados',
        iconClass: 'fa-home',
      })
  }])

**My HTML Page (Shell Controller )**

  <div ng-controller="ShellCtrl">
   
    <eeh-navigation-sidebar menu-name="'bar'"
                            sidebar-is-collapsed="true"
                            sidebar-collapsed-icon-class="'fa-arrow-right'"
                            sidebar-expanded-icon-class="'fa-arrow-left'"
                            search-input-is-visible="false"
    >
        <ui-view></ui-view>
    </eeh-navigation-sidebar>
  </div>

**and that is a example page where i consuming my sidebar:**

<div ng-include="'components/shell/shell.html'"></div>
<div class="container-fluid" ng-controller="DeParaProgramacaoCtrl as ctrl">
	<div class="row">
		<div class="col-md-3">
			<h6><b>Distribuidor</b></h6>
			<ui-select ng-model="ctrl.objDistribuidor.selected"
			theme="bootstrap"
			reset-search-input="false"
			style="width: 100%;"
			on-select="getFilmes()"
			title="Escolha distribuidor">
			<ui-select-match placeholder="Escolha o Distribuidor">{{$select.selected.nome}}</ui-select-match>
			<ui-select-choices repeat="d in distribuidores |filter: $select.search">
			<div ng-bind-html="d.nome | highlight: $select.search"></div>
			</ui-select-choices>
			<ui-select-no-choice>
			Não encontrei distribuidores
			</ui-select-no-choice>
			</ui-select>
		</div>
		<div class="col-md-1" style="padding-top: 35px">
			<button style="width:100%" class="btn-primary" ng-click="carregardeParaFilmes()">Filtrar</button>
		</div>
	</div><br>
	<div class="row">
		<div class="col-md-12">
			<div ag-grid="gridDeParaProgramacao" id="gridDeParaProgramacao" class="ag-fresh" style="height: 500px;">
			</div>
		</div>
	</div>
</div>

**this the result:**
![image](https://cloud.githubusercontent.com/assets/377236/21372332/8b49966a-c6fd-11e6-842a-647d35aa715b.png)

![image](https://cloud.githubusercontent.com/assets/377236/21372337/9974b256-c6fd-11e6-8d93-5e49c0d24002.png)

Can u help me!!

**Comment by niltonjacintho** [comment]
In fact my users need to have access to this menu on every page on my app! How  can i do this without get my design crazy!

**Comment by ethanhann** [comment]
The sidebar directive transcludes all your content into a wrapper div to control padding when the sidebar is collapsed/expanded. You should include the directive in a ui-router state toward the top of your state hierarchy. You need a nested state hierarchy for your content to show up in the wrapper div, i.e. for ui-view to display anything..
