### ISSUE TITLE
Unable to set unique identifiers for menu items

### ISSUE THREAD

**Issue by Blaatschaap** [ethanhann/eeh-navigation#65]
For use in automated protractor tests, we'd like to be able to add unique id's to menu options. Something like this:
```
                .menuItem('navbar.language.en', {
                    text: 'en',
                    click: function() {
                        changeLanguage('en');
                    },
                    name: 'enLanguage'
                })
```

I can currently find no way to do this in the docs. Am I missing something?

**Comment by ethanhann** [comment]
Resolved by 70ae36a1ad35e2cd9a9d12b85637302b5ecb6790

Each menu item now has an auto-generated ID, but you can specify a custom ID like this:

```js
.menuItem('navbar.language.en', {
    text: 'en',
    click: function() {
        changeLanguage('en');
    },
    id: 'enLanguage'
})
```
