### ISSUE TITLE
include additional script tags in example

### ISSUE THREAD

**Issue by uuunk** [ethanhann/eeh-navigation#7]
I know it you mention the necessary dependencies in the "about" section, and it's probably just that I'm a rookie in w/ front end dev, but it would be helpful to also mention the required tags in the "getting started" guide.  (e.g. `<script type="text/javascript" src="/bower_components/jquery/dist/jquery.js"></script>`)

**Comment by ethanhann** [comment]
I added  the required tags in the "Getting Started" doc. 

I'll give you a pro tip since you mentioned you're a front-end rookie. You can use [wiredep](https://github.com/taptapship/wiredep) with Grunt or Gulp to automatically include your Bower dependencies as a part of your build process.

**Comment by uuunk** [comment]
Ah very nice! Thanks!
